In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("stock_price_f.csv")

In [4]:
df.head()

,Date,Stock,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2000-01-03 00:00:00+05:30,RELIANCE.NS,12.439688,13.183451,12.439688,13.183451,62409578,0.0,0.0
1,2000-01-04 00:00:00+05:30,RELIANCE.NS,13.534378,14.238858,13.162497,14.238858,132872110,0.0,0.0
2,2000-01-05 00:00:00+05:30,RELIANCE.NS,13.442721,15.079523,13.442721,14.796683,375789847,0.0,0.0
3,2000-01-06 00:00:00+05:30,RELIANCE.NS,15.137136,15.749955,15.137136,15.417356,219621124,0.0,0.0
4,2000-01-07 00:00:00+05:30,RELIANCE.NS,15.451403,16.650852,15.346648,16.475386,278281260,0.0,0.0

In [5]:
df.shape

(120203, 9)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120203 entries, 0 to 120202
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          120203 non-null  object
 1   Stock         120203 non-null  object
 2   Open          120203 non-null  float64
 3   High          120203 non-null  float64
 4   Low           120203 non-null  float64
 5   Close         120203 non-null  float64
 6   Volume        120203 non-null  int64
 7   Dividends     120203 non-null  float64
 8   Stock Splits  120203 non-null  float64
dtypes: float64(6), int64(1), object(2)
memory usage: 8.3+ MB

In [7]:
df.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,120203.000000,120203.000000,120203.000000,120203.000000,1.202030e+05,120203.000000,120203.000000
mean,733.677242,742.125405,724.505203,733.171364,1.019375e+07,0.029345,0.001265
std,1490.156873,1505.387113,1473.445972,1489.090932,1.707314e+07,0.923548,0.080971
min,-0.012941,-0.012989,-0.012428,-0.012845,0.000000e+00,0.000000,0.000000
25%,60.811140,62.021089,59.508520,60.775988,1.386260e+06,0.000000,0.000000
50%,222.583230,225.694608,219.365043,222.456070,4.840759e+06,0.000000,0.000000
75%,714.104187,722.105162,703.682280,712.979614,1.230179e+07,0.000000,0.000000
max,13239.701752,13406.889352,13132.314243,13351.095703,6.322896e+08,125.000000,10.000000

In [14]:
df['Date'] = pd.to_datetime(df['Date'])

In [16]:
df['Stock'].nunique()

20

In [17]:
(df[['Open', 'High', 'Low', 'Close']] < 0).sum()

Open     47
High     47
Low      47
Close    47
dtype: int64

In [18]:
(df['Volume'] == 0).sum()

np.int64(1241)

In [19]:
(
    (df['High'] < df['Open']) |
    (df['High'] < df['Close']) |
    (df['High'] < df['Low']) |
    (df['Low'] > df['Open']) |
    (df['Low'] > df['Close'])
).sum()

np.int64(99)

In [20]:
df['Stock'].value_counts().head(20)

Stock
HDFCBANK.NS      6340
INFY.NS          6340
WIPRO.NS         6340
HINDUNILVR.NS    6340
SUNPHARMA.NS     6340
TITAN.NS         6340
SBIN.NS          6338
RELIANCE.NS      6337
ITC.NS           6337
AXISBANK.NS      6337
KOTAKBANK.NS     5949
LT.NS            5690
ADANIENT.NS      5689
ASIANPAINT.NS    5687
BAJFINANCE.NS    5687
ICICIBANK.NS     5687
BHARTIARTL.NS    5687
TCS.NS           5658
ULTRACEMCO.NS    5657
MARUTI.NS        5423
Name: count, dtype: int64

In [21]:
df.isnull().sum()

Date            0
Stock           0
Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [22]:
df[df['Volume'] == 0][
    ['Date', 'Stock', 'Open', 'High', 'Low', 'Close', 'Volume']
].head(20)

,Date,Stock,Open,High,Low,Close,Volume
17,2000-01-26 00:00:00+05:30,RELIANCE.NS,16.758226,16.758226,16.758226,16.758226,0
54,2000-03-17 00:00:00+05:30,RELIANCE.NS,12.300888,12.300888,12.300888,12.300888,0
55,2000-03-20 00:00:00+05:30,RELIANCE.NS,12.300888,12.300888,12.300888,12.300888,0
74,2000-04-14 00:00:00+05:30,RELIANCE.NS,16.669378,16.669378,16.669378,16.669378,0
79,2000-04-21 00:00:00+05:30,RELIANCE.NS,18.106068,18.106068,18.106068,18.106068,0
85,2000-05-01 00:00:00+05:30,RELIANCE.NS,18.497404,18.497404,18.497404,18.497404,0
161,2000-08-15 00:00:00+05:30,RELIANCE.NS,17.655762,17.655762,17.655762,17.655762,0
174,2000-09-01 00:00:00+05:30,RELIANCE.NS,18.041742,18.041742,18.041742,18.041742,0
195,2000-10-02 00:00:00+05:30,RELIANCE.NS,18.360710,18.360710,18.360710,18.360710,0
255,2000-12-25 00:00:00+05:30,RELIANCE.NS,18.130192,18.130192,18.130192,18.130192,0
279,2001-01-26 00:00:00+05:30,RELIANCE.NS,20.462139,20.462139,20.462139,20.462139,0
306,2001-03-06 00:00:00+05:30,RELIANCE.NS,21.906868,21.906868,21.906868,21.906868,0
328,2001-04-05 00:00:00+05:30,RELIANCE.NS,20.537188,20.537188,20.537188,20.537188,0
334,2001-04-13 00:00:00+05:30,RELIANCE.NS,15.940308,15.940308,15.940308,15.940308,0
346,2001-05-01 00:00:00+05:30,RELIANCE.NS,18.745920,18.745920,18.745920,18.745920,0
422,2001-08-15 00:00:00+05:30,RELIANCE.NS,17.571907,17.571907,17.571907,17.571907,0
427,2001-08-22 00:00:00+05:30,RELIANCE.NS,17.454231,17.454231,17.454231,17.454231,0
456,2001-10-02 00:00:00+05:30,RELIANCE.NS,14.205851,14.205851,14.205851,14.205851,0
474,2001-10-26 00:00:00+05:30,RELIANCE.NS,14.443939,14.443939,14.443939,14.443939,0
489,2001-11-16 00:00:00+05:30,RELIANCE.NS,15.218407,15.218407,15.218407,15.218407,0

In [23]:
df[df['Volume'] == 0]['Stock'].value_counts()

Stock
TCS.NS           311
INFY.NS           61
HDFCBANK.NS       61
HINDUNILVR.NS     61
SUNPHARMA.NS      61
WIPRO.NS          61
TITAN.NS          61
AXISBANK.NS       59
SBIN.NS           59
RELIANCE.NS       58
ITC.NS            57
LT.NS             57
KOTAKBANK.NS      45
ULTRACEMCO.NS     39
ADANIENT.NS       34
BAJFINANCE.NS     34
ICICIBANK.NS      32
BHARTIARTL.NS     32
ASIANPAINT.NS     32
MARUTI.NS         26
Name: count, dtype: int64

In [24]:
invalid_ohlc = (
    (df['High'] < df['Open']) |
    (df['High'] < df['Close']) |
    (df['High'] < df['Low']) |
    (df['Low'] > df['Open']) |
    (df['Low'] > df['Close'])
)

df[invalid_ohlc][
    ['Date', 'Stock', 'Open', 'High', 'Low', 'Close', 'Volume']
]

,Date,Stock,Open,High,Low,Close,Volume
66,2000-04-04 00:00:00+05:30,RELIANCE.NS,17.075103,17.075103,15.836371,15.836371,189486468
334,2001-04-13 00:00:00+05:30,RELIANCE.NS,15.940308,15.940308,15.940308,15.940308,0
489,2001-11-16 00:00:00+05:30,RELIANCE.NS,15.218407,15.218407,15.218407,15.218407,0
607,2002-05-01 00:00:00+05:30,RELIANCE.NS,15.234822,15.234822,15.234822,15.234822,0
6383,2002-10-15 00:00:00+05:30,TCS.NS,24.218763,24.218763,24.218763,24.218763,0
...,...,...,...,...,...,...,...
114557,2002-08-29 00:00:00+05:30,ADANIENT.NS,-0.010676,-0.010676,-0.010539,-0.010594,489146
114558,2002-08-30 00:00:00+05:30,ADANIENT.NS,-0.010594,-0.010641,-0.010546,-0.010621,488768
114559,2002-09-02 00:00:00+05:30,ADANIENT.NS,-0.010662,-0.010806,-0.010662,-0.010737,514408
114560,2002-09-03 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010758,-0.010628,-0.010710,493035
114924,2004-01-26 00:00:00+05:30,ADANIENT.NS,0.936609,0.936609,0.936609,0.936609,0

In [25]:
df[df[['Open', 'High', 'Low', 'Close']].lt(0).any(axis=1)][
    ['Date', 'Stock', 'Open', 'High', 'Low', 'Close', 'Volume']
]

,Date,Stock,Open,High,Low,Close,Volume
114514,2002-07-01 00:00:00+05:30,ADANIENT.NS,-0.012181,-0.012517,-0.011914,-0.012168,1080397
114515,2002-07-02 00:00:00+05:30,ADANIENT.NS,-0.012380,-0.012421,-0.012113,-0.012263,1016147
114516,2002-07-03 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012387,-0.012188,-0.012263,980394
114517,2002-07-04 00:00:00+05:30,ADANIENT.NS,-0.012318,-0.012517,-0.012318,-0.012332,972747
114518,2002-07-05 00:00:00+05:30,ADANIENT.NS,-0.012400,-0.012400,-0.012257,-0.012304,974496
114519,2002-07-08 00:00:00+05:30,ADANIENT.NS,-0.012455,-0.012989,-0.012188,-0.012845,1061686
114520,2002-07-09 00:00:00+05:30,ADANIENT.NS,-0.012797,-0.012866,-0.012428,-0.012510,1024719
114521,2002-07-10 00:00:00+05:30,ADANIENT.NS,-0.012592,-0.012592,-0.012387,-0.012496,946638
114522,2002-07-11 00:00:00+05:30,ADANIENT.NS,-0.012941,-0.012941,-0.012257,-0.012291,968220
114523,2002-07-12 00:00:00+05:30,ADANIENT.NS,-0.012428,-0.012530,-0.012318,-0.012387,967763
114524,2002-07-15 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012311,-0.012085,-0.012133,974157
114525,2002-07-16 00:00:00+05:30,ADANIENT.NS,-0.012181,-0.012332,-0.012181,-0.012243,959138
114526,2002-07-17 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012250,-0.012113,-0.012147,955902
114527,2002-07-18 00:00:00+05:30,ADANIENT.NS,-0.012476,-0.012476,-0.012188,-0.012291,958081
114528,2002-07-19 00:00:00+05:30,ADANIENT.NS,-0.012387,-0.012387,-0.012120,-0.012243,1022018
114529,2002-07-22 00:00:00+05:30,ADANIENT.NS,-0.012044,-0.012298,-0.011873,-0.011955,959229
114530,2002-07-23 00:00:00+05:30,ADANIENT.NS,-0.011634,-0.012174,-0.011634,-0.011955,950108
114531,2002-07-24 00:00:00+05:30,ADANIENT.NS,-0.011839,-0.011996,-0.011641,-0.011641,1004507
114532,2002-07-25 00:00:00+05:30,ADANIENT.NS,-0.011976,-0.012161,-0.011565,-0.011750,929688
114533,2002-07-26 00:00:00+05:30,ADANIENT.NS,-0.011463,-0.011463,-0.011305,-0.011387,934529
114534,2002-07-29 00:00:00+05:30,ADANIENT.NS,-0.011565,-0.011565,-0.010970,-0.011107,955236
114535,2002-07-30 00:00:00+05:30,ADANIENT.NS,-0.011565,-0.011565,-0.010949,-0.010984,972108
114536,2002-07-31 00:00:00+05:30,ADANIENT.NS,-0.011155,-0.011155,-0.010676,-0.010881,961513
114537,2002-08-01 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.011257,-0.010949,-0.011011,953331
114538,2002-08-02 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.010949,-0.010724,-0.010902,939461
114539,2002-08-05 00:00:00+05:30,ADANIENT.NS,-0.011497,-0.011497,-0.010689,-0.010881,982116
114540,2002-08-06 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.010949,-0.010683,-0.010730,971195
114541,2002-08-07 00:00:00+05:30,ADANIENT.NS,-0.011086,-0.011086,-0.010847,-0.010929,966576
114542,2002-08-08 00:00:00+05:30,ADANIENT.NS,-0.011155,-0.011155,-0.010710,-0.010765,971443
114543,2002-08-09 00:00:00+05:30,ADANIENT.NS,-0.010813,-0.010915,-0.010744,-0.010847,918884
114544,2002-08-12 00:00:00+05:30,ADANIENT.NS,-0.010888,-0.010943,-0.010813,-0.010895,489590
114545,2002-08-13 00:00:00+05:30,ADANIENT.NS,-0.010908,-0.010943,-0.010813,-0.010854,384772
114546,2002-08-14 00:00:00+05:30,ADANIENT.NS,-0.010922,-0.010922,-0.010628,-0.010744,482452
114547,2002-08-15 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010744,-0.010744,-0.010744,0
114548,2002-08-16 00:00:00+05:30,ADANIENT.NS,-0.010717,-0.010813,-0.010511,-0.010573,520671
114549,2002-08-19 00:00:00+05:30,ADANIENT.NS,-0.010813,-0.010813,-0.010477,-0.010566,501059
114550,2002-08-20 00:00:00+05:30,ADANIENT.NS,-0.010669,-0.010669,-0.010539,-0.010559,507936
114551,2002-08-21 00:00:00+05:30,ADANIENT.NS,-0.010696,-0.010765,-0.010607,-0.010662,507062
114552,2002-08-22 00:00:00+05:30,ADANIENT.NS,-0.010696,-0.010778,-0.010607,-0.010696,495383
114553,2002-08-23 00:00:00+05:30,ADANIENT.NS,-0.010751,-0.010813,-0.010607,-0.010730,519588
114554,2002-08-26 00:00:00+05:30,ADANIENT.NS,-0.010806,-0.010949,-0.010655,-0.010696,552014
114555,2002-08-27 00:00:00+05:30,ADANIENT.NS,-0.010730,-0.010792,-0.010573,-0.010635,504152
114556,2002-08-28 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010744,-0.010580,-0.010655,491338
114557,2002-08-29 00:00:00+05:30,ADANIENT.NS,-0.010676,-0.010676,-0.010539,-0.010594,489146
114558,2002-08-30 00:00:00+05:30,ADANIENT.NS,-0.010594,-0.010641,-0.010546,-0.010621,488768
114559,2002-09-02 00:00:00+05:30,ADANIENT.NS,-0.010662,-0.010806,-0.010662,-0.010737,514408
114560,2002-09-03 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010758,-0.010628,-0.010710,493035

In [26]:
negative_prices = df[df[['Open', 'High', 'Low', 'Close']].lt(0).any(axis=1)]

negative_prices['Stock'].value_counts()

Stock
ADANIENT.NS    47
Name: count, dtype: int64

In [27]:
negative_prices.shape

(47, 9)

In [30]:
len(set(negative_prices.index) & set(df[invalid_ohlc].index))

46

In [31]:
df.duplicated(subset=['Stock', 'Date']).sum()

np.int64(0)

In [37]:
df.loc[
    negative_prices.index,
    ['Date', 'Stock', 'Open', 'High', 'Low', 'Close', 'Volume']
].head(50)

,Date,Stock,Open,High,Low,Close,Volume
114514,2002-07-01 00:00:00+05:30,ADANIENT.NS,-0.012181,-0.012517,-0.011914,-0.012168,1080397
114515,2002-07-02 00:00:00+05:30,ADANIENT.NS,-0.012380,-0.012421,-0.012113,-0.012263,1016147
114516,2002-07-03 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012387,-0.012188,-0.012263,980394
114517,2002-07-04 00:00:00+05:30,ADANIENT.NS,-0.012318,-0.012517,-0.012318,-0.012332,972747
114518,2002-07-05 00:00:00+05:30,ADANIENT.NS,-0.012400,-0.012400,-0.012257,-0.012304,974496
114519,2002-07-08 00:00:00+05:30,ADANIENT.NS,-0.012455,-0.012989,-0.012188,-0.012845,1061686
114520,2002-07-09 00:00:00+05:30,ADANIENT.NS,-0.012797,-0.012866,-0.012428,-0.012510,1024719
114521,2002-07-10 00:00:00+05:30,ADANIENT.NS,-0.012592,-0.012592,-0.012387,-0.012496,946638
114522,2002-07-11 00:00:00+05:30,ADANIENT.NS,-0.012941,-0.012941,-0.012257,-0.012291,968220
114523,2002-07-12 00:00:00+05:30,ADANIENT.NS,-0.012428,-0.012530,-0.012318,-0.012387,967763
114524,2002-07-15 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012311,-0.012085,-0.012133,974157
114525,2002-07-16 00:00:00+05:30,ADANIENT.NS,-0.012181,-0.012332,-0.012181,-0.012243,959138
114526,2002-07-17 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012250,-0.012113,-0.012147,955902
114527,2002-07-18 00:00:00+05:30,ADANIENT.NS,-0.012476,-0.012476,-0.012188,-0.012291,958081
114528,2002-07-19 00:00:00+05:30,ADANIENT.NS,-0.012387,-0.012387,-0.012120,-0.012243,1022018
114529,2002-07-22 00:00:00+05:30,ADANIENT.NS,-0.012044,-0.012298,-0.011873,-0.011955,959229
114530,2002-07-23 00:00:00+05:30,ADANIENT.NS,-0.011634,-0.012174,-0.011634,-0.011955,950108
114531,2002-07-24 00:00:00+05:30,ADANIENT.NS,-0.011839,-0.011996,-0.011641,-0.011641,1004507
114532,2002-07-25 00:00:00+05:30,ADANIENT.NS,-0.011976,-0.012161,-0.011565,-0.011750,929688
114533,2002-07-26 00:00:00+05:30,ADANIENT.NS,-0.011463,-0.011463,-0.011305,-0.011387,934529
114534,2002-07-29 00:00:00+05:30,ADANIENT.NS,-0.011565,-0.011565,-0.010970,-0.011107,955236
114535,2002-07-30 00:00:00+05:30,ADANIENT.NS,-0.011565,-0.011565,-0.010949,-0.010984,972108
114536,2002-07-31 00:00:00+05:30,ADANIENT.NS,-0.011155,-0.011155,-0.010676,-0.010881,961513
114537,2002-08-01 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.011257,-0.010949,-0.011011,953331
114538,2002-08-02 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.010949,-0.010724,-0.010902,939461
114539,2002-08-05 00:00:00+05:30,ADANIENT.NS,-0.011497,-0.011497,-0.010689,-0.010881,982116
114540,2002-08-06 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.010949,-0.010683,-0.010730,971195
114541,2002-08-07 00:00:00+05:30,ADANIENT.NS,-0.011086,-0.011086,-0.010847,-0.010929,966576
114542,2002-08-08 00:00:00+05:30,ADANIENT.NS,-0.011155,-0.011155,-0.010710,-0.010765,971443
114543,2002-08-09 00:00:00+05:30,ADANIENT.NS,-0.010813,-0.010915,-0.010744,-0.010847,918884
114544,2002-08-12 00:00:00+05:30,ADANIENT.NS,-0.010888,-0.010943,-0.010813,-0.010895,489590
114545,2002-08-13 00:00:00+05:30,ADANIENT.NS,-0.010908,-0.010943,-0.010813,-0.010854,384772
114546,2002-08-14 00:00:00+05:30,ADANIENT.NS,-0.010922,-0.010922,-0.010628,-0.010744,482452
114547,2002-08-15 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010744,-0.010744,-0.010744,0
114548,2002-08-16 00:00:00+05:30,ADANIENT.NS,-0.010717,-0.010813,-0.010511,-0.010573,520671
114549,2002-08-19 00:00:00+05:30,ADANIENT.NS,-0.010813,-0.010813,-0.010477,-0.010566,501059
114550,2002-08-20 00:00:00+05:30,ADANIENT.NS,-0.010669,-0.010669,-0.010539,-0.010559,507936
114551,2002-08-21 00:00:00+05:30,ADANIENT.NS,-0.010696,-0.010765,-0.010607,-0.010662,507062
114552,2002-08-22 00:00:00+05:30,ADANIENT.NS,-0.010696,-0.010778,-0.010607,-0.010696,495383
114553,2002-08-23 00:00:00+05:30,ADANIENT.NS,-0.010751,-0.010813,-0.010607,-0.010730,519588
114554,2002-08-26 00:00:00+05:30,ADANIENT.NS,-0.010806,-0.010949,-0.010655,-0.010696,552014
114555,2002-08-27 00:00:00+05:30,ADANIENT.NS,-0.010730,-0.010792,-0.010573,-0.010635,504152
114556,2002-08-28 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010744,-0.010580,-0.010655,491338
114557,2002-08-29 00:00:00+05:30,ADANIENT.NS,-0.010676,-0.010676,-0.010539,-0.010594,489146
114558,2002-08-30 00:00:00+05:30,ADANIENT.NS,-0.010594,-0.010641,-0.010546,-0.010621,488768
114559,2002-09-02 00:00:00+05:30,ADANIENT.NS,-0.010662,-0.010806,-0.010662,-0.010737,514408
114560,2002-09-03 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010758,-0.010628,-0.010710,493035

In [38]:
negative_mask = df[['Open', 'High', 'Low', 'Close']].lt(0).any(axis=1)

invalid_without_negative = df[invalid_ohlc & ~negative_mask]

invalid_without_negative[
    ['Date', 'Stock', 'Open', 'High', 'Low', 'Close', 'Volume']
].head(60)

,Date,Stock,Open,High,Low,Close,Volume
66,2000-04-04 00:00:00+05:30,RELIANCE.NS,17.075103,17.075103,15.836371,15.836371,189486468
334,2001-04-13 00:00:00+05:30,RELIANCE.NS,15.940308,15.940308,15.940308,15.940308,0
489,2001-11-16 00:00:00+05:30,RELIANCE.NS,15.218407,15.218407,15.218407,15.218407,0
607,2002-05-01 00:00:00+05:30,RELIANCE.NS,15.234822,15.234822,15.234822,15.234822,0
6383,2002-10-15 00:00:00+05:30,TCS.NS,24.218763,24.218763,24.218763,24.218763,0
6491,2003-03-14 00:00:00+05:30,TCS.NS,26.764318,26.764318,26.764318,26.764318,0
6925,2004-11-15 00:00:00+05:30,TCS.NS,95.751320,95.751320,95.751320,95.751320,0
6934,2004-11-26 00:00:00+05:30,TCS.NS,97.359535,97.359535,97.359535,97.359535,0
11999,2000-01-07 00:00:00+05:30,INFY.NS,61.325985,61.325985,61.325985,61.325985,971392
12001,2000-01-11 00:00:00+05:30,INFY.NS,61.674072,64.477439,59.135857,59.135857,15658368
12025,2000-02-14 00:00:00+05:30,INFY.NS,100.374100,100.374100,100.374100,100.374100,1518912
12038,2000-03-02 00:00:00+05:30,INFY.NS,94.704747,95.691063,92.811069,95.691063,1607040
12069,2000-04-14 00:00:00+05:30,INFY.NS,86.631981,86.631981,86.631981,86.631981,0
12327,2001-04-11 00:00:00+05:30,INFY.NS,37.545856,38.325296,30.070351,30.070351,41200640
12451,2001-10-02 00:00:00+05:30,INFY.NS,21.803333,21.803333,21.803333,21.803333,0
12484,2001-11-16 00:00:00+05:30,INFY.NS,30.532764,30.532764,30.532764,30.532764,0
12678,2002-08-15 00:00:00+05:30,INFY.NS,29.778316,29.778316,29.778316,29.778316,0
13055,2004-01-26 00:00:00+05:30,INFY.NS,52.091019,52.091019,52.091019,52.091019,0
13112,2004-04-14 00:00:00+05:30,INFY.NS,52.401020,52.401020,52.401020,52.401020,0
14268,2008-11-27 00:00:00+05:30,INFY.NS,97.566971,97.566971,97.566971,97.566971,0
18403,2000-04-06 00:00:00+05:30,HDFCBANK.NS,8.301004,8.501512,7.721538,7.721538,1670120
19449,2004-04-09 00:00:00+05:30,HDFCBANK.NS,15.758716,15.758716,15.758716,15.758716,0
24892,2003-05-01 00:00:00+05:30,ICICIBANK.NS,15.767154,15.767154,15.767154,15.767154,0
30447,2000-05-01 00:00:00+05:30,SBIN.NS,13.088063,13.088063,13.088063,13.088063,0
31079,2002-10-02 00:00:00+05:30,SBIN.NS,15.448785,15.448785,15.448785,15.448785,0
31875,2005-11-04 00:00:00+05:30,SBIN.NS,59.681915,59.681915,59.681915,59.681915,0
36792,2002-11-06 00:00:00+05:30,LT.NS,31.635120,31.635120,31.635120,31.635120,0
37175,2004-04-26 00:00:00+05:30,LT.NS,102.114807,102.114807,102.114807,102.114807,0
42817,2001-08-22 00:00:00+05:30,ITC.NS,7.916252,7.916252,7.916252,7.916252,0
42879,2001-11-16 00:00:00+05:30,ITC.NS,7.413278,7.413278,7.413278,7.413278,0
42970,2002-03-25 00:00:00+05:30,ITC.NS,7.676972,7.676972,7.676972,7.676972,0
42997,2002-05-01 00:00:00+05:30,ITC.NS,6.832716,6.832716,6.832716,6.832716,0
43073,2002-08-15 00:00:00+05:30,ITC.NS,7.636112,7.636112,7.636112,7.636112,0
43107,2002-10-02 00:00:00+05:30,ITC.NS,7.194844,7.194844,7.194844,7.194844,0
43132,2002-11-06 00:00:00+05:30,ITC.NS,6.947910,6.947910,6.947910,6.947910,0
43167,2002-12-25 00:00:00+05:30,ITC.NS,7.333257,7.333257,7.333257,7.333257,0
43248,2003-04-18 00:00:00+05:30,ITC.NS,7.567458,7.567458,7.567458,7.567458,0
43257,2003-05-01 00:00:00+05:30,ITC.NS,7.562476,7.562476,7.562476,7.562476,0
43666,2004-11-26 00:00:00+05:30,ITC.NS,14.697599,14.697599,14.697599,14.697599,0
49061,2001-04-13 00:00:00+05:30,HINDUNILVR.NS,117.442207,117.442207,117.442207,117.442207,0
49073,2001-05-01 00:00:00+05:30,HINDUNILVR.NS,117.581879,117.581879,117.581879,117.581879,0
49154,2001-08-22 00:00:00+05:30,HINDUNILVR.NS,126.428185,126.428185,126.428185,126.428185,0
49334,2002-05-01 00:00:00+05:30,HINDUNILVR.NS,115.717690,115.717690,115.717690,115.717690,0
49453,2002-10-15 00:00:00+05:30,HINDUNILVR.NS,99.814232,99.814232,99.814232,99.814232,0
49540,2003-02-13 00:00:00+05:30,HINDUNILVR.NS,97.205048,97.205048,97.205048,97.205048,0
49841,2004-04-09 00:00:00+05:30,HINDUNILVR.NS,89.613518,89.613518,89.613518,89.613518,0
50242,2005-11-04 00:00:00+05:30,HINDUNILVR.NS,107.599220,107.599220,107.599220,107.599220,0
55684,2004-11-15 00:00:00+05:30,BAJFINANCE.NS,0.963990,0.963990,0.963990,0.963990,0
78935,2004-04-26 00:00:00+05:30,MARUTI.NS,497.947632,497.947632,497.947632,497.947632,0
84184,2000-02-18 00:00:00+05:30,SUNPHARMA.NS,15.201955,15.201955,15.201955,15.201955,1350775
85264,2004-04-09 00:00:00+05:30,SUNPHARMA.NS,27.634459,27.634459,27.634459,27.634459,0
102614,2002-12-25 00:00:00+05:30,ASIANPAINT.NS,15.895419,15.895419,15.895419,15.895419,0
114924,2004-01-26 00:00:00+05:30,ADANIENT.NS,0.936609,0.936609,0.936609,0.936609,0

In [39]:
invalid_without_negative['Stock'].value_counts()

Stock
INFY.NS          12
ITC.NS           11
HINDUNILVR.NS     8
RELIANCE.NS       4
TCS.NS            4
SBIN.NS           3
LT.NS             2
HDFCBANK.NS       2
SUNPHARMA.NS      2
ICICIBANK.NS      1
BAJFINANCE.NS     1
MARUTI.NS         1
ASIANPAINT.NS     1
ADANIENT.NS       1
Name: count, dtype: int64

In [40]:
negative_mask = df[['Open', 'High', 'Low', 'Close']].lt(0).any(axis=1)

invalid_ohlc = (
    (df['High'] < df['Open']) |
    (df['High'] < df['Close']) |
    (df['High'] < df['Low']) |
    (df['Low'] > df['Open']) |
    (df['Low'] > df['Close'])
)

In [41]:
print("Negative-price rows:", negative_mask.sum())
print("Invalid OHLC rows:", invalid_ohlc.sum())
print("Invalid OHLC excluding negative rows:",
      (invalid_ohlc & ~negative_mask).sum())

Negative-price rows: 47
Invalid OHLC rows: 99
Invalid OHLC excluding negative rows: 53

In [42]:
invalid_without_negative.assign(
    High_less_than_Open=invalid_without_negative['High'] < invalid_without_negative['Open'],
    High_less_than_Close=invalid_without_negative['High'] < invalid_without_negative['Close'],
    High_less_than_Low=invalid_without_negative['High'] < invalid_without_negative['Low'],
    Low_greater_than_Open=invalid_without_negative['Low'] > invalid_without_negative['Open'],
    Low_greater_than_Close=invalid_without_negative['Low'] > invalid_without_negative['Close']
)[[
    'Stock',
    'High_less_than_Open',
    'High_less_than_Close',
    'High_less_than_Low',
    'Low_greater_than_Open',
    'Low_greater_than_Close'
]].sum()

Stock                     RELIANCE.NSRELIANCE.NSRELIANCE.NSRELIANCE.NSTC...
High_less_than_Open                                                       0
High_less_than_Close                                                     34
High_less_than_Low                                                        0
Low_greater_than_Open                                                     0
Low_greater_than_Close                                                   19
dtype: object

In [43]:
invalid_without_negative[
    ['Date', 'Stock', 'Open', 'High', 'Low', 'Close', 'Volume']
].sort_values(['Stock', 'Date']).to_string(index=False)

'                     Date         Stock       Open       High        Low      Close    Volume\n2004-01-26 00:00:00+05:30   ADANIENT.NS   0.936609   0.936609   0.936609   0.936609         0\n2002-12-25 00:00:00+05:30 ASIANPAINT.NS  15.895419  15.895419  15.895419  15.895419         0\n2004-11-15 00:00:00+05:30 BAJFINANCE.NS   0.963990   0.963990   0.963990   0.963990         0\n2000-04-06 00:00:00+05:30   HDFCBANK.NS   8.301004   8.501512   7.721538   7.721538   1670120\n2004-04-09 00:00:00+05:30   HDFCBANK.NS  15.758716  15.758716  15.758716  15.758716         0\n2001-04-13 00:00:00+05:30 HINDUNILVR.NS 117.442207 117.442207 117.442207 117.442207         0\n2001-05-01 00:00:00+05:30 HINDUNILVR.NS 117.581879 117.581879 117.581879 117.581879         0\n2001-08-22 00:00:00+05:30 HINDUNILVR.NS 126.428185 126.428185 126.428185 126.428185         0\n2002-05-01 00:00:00+05:30 HINDUNILVR.NS 115.717690 115.717690 115.717690 115.717690         0\n2002-10-15 00:00:00+05:30 HINDUNILVR.NS  99.814232  99.814232  99.814232  99.814232         0\n2003-02-13 00:00:00+05:30 HINDUNILVR.NS  97.205048  97.205048  97.205048  97.205048         0\n2004-04-09 00:00:00+05:30 HINDUNILVR.NS  89.613518  89.613518  89.613518  89.613518         0\n2005-11-04 00:00:00+05:30 HINDUNILVR.NS 107.599220 107.599220 107.599220 107.599220         0\n2003-05-01 00:00:00+05:30  ICICIBANK.NS  15.767154  15.767154  15.767154  15.767154         0\n2000-01-07 00:00:00+05:30       INFY.NS  61.325985  61.325985  61.325985  61.325985    971392\n2000-01-11 00:00:00+05:30       INFY.NS  61.674072  64.477439  59.135857  59.135857  15658368\n2000-02-14 00:00:00+05:30       INFY.NS 100.374100 100.374100 100.374100 100.374100   1518912\n2000-03-02 00:00:00+05:30       INFY.NS  94.704747  95.691063  92.811069  95.691063   1607040\n2000-04-14 00:00:00+05:30       INFY.NS  86.631981  86.631981  86.631981  86.631981         0\n2001-04-11 00:00:00+05:30       INFY.NS  37.545856  38.325296  30.070351  30.070351  41200640\n2001-10-02 00:00:00+05:30       INFY.NS  21.803333  21.803333  21.803333  21.803333         0\n2001-11-16 00:00:00+05:30       INFY.NS  30.532764  30.532764  30.532764  30.532764         0\n2002-08-15 00:00:00+05:30       INFY.NS  29.778316  29.778316  29.778316  29.778316         0\n2004-01-26 00:00:00+05:30       INFY.NS  52.091019  52.091019  52.091019  52.091019         0\n2004-04-14 00:00:00+05:30       INFY.NS  52.401020  52.401020  52.401020  52.401020         0\n2008-11-27 00:00:00+05:30       INFY.NS  97.566971  97.566971  97.566971  97.566971         0\n2001-08-22 00:00:00+05:30        ITC.NS   7.916252   7.916252   7.916252   7.916252         0\n2001-11-16 00:00:00+05:30        ITC.NS   7.413278   7.413278   7.413278   7.413278         0\n2002-03-25 00:00:00+05:30        ITC.NS   7.676972   7.676972   7.676972   7.676972         0\n2002-05-01 00:00:00+05:30        ITC.NS   6.832716   6.832716   6.832716   6.832716         0\n2002-08-15 00:00:00+05:30        ITC.NS   7.636112   7.636112   7.636112   7.636112         0\n2002-10-02 00:00:00+05:30        ITC.NS   7.194844   7.194844   7.194844   7.194844         0\n2002-11-06 00:00:00+05:30        ITC.NS   6.947910   6.947910   6.947910   6.947910         0\n2002-12-25 00:00:00+05:30        ITC.NS   7.333257   7.333257   7.333257   7.333257         0\n2003-04-18 00:00:00+05:30        ITC.NS   7.567458   7.567458   7.567458   7.567458         0\n2003-05-01 00:00:00+05:30        ITC.NS   7.562476   7.562476   7.562476   7.562476         0\n2004-11-26 00:00:00+05:30        ITC.NS  14.697599  14.697599  14.697599  14.697599         0\n2002-11-06 00:00:00+05:30         LT.NS  31.635120  31.635120  31.635120  31.635120         0\n2004-04-26 00:00:00+05:30         LT.NS 102.114807 102.114807 102.114807 102.114807         0\n2004-04-26 00:00:00+05:30     MARUTI.NS 497.947632 497.947632 497.947632 497.947632         0\n2000-04-04 00:00:00+05:30   RELIANCE.NS  17.075103  17.075103  15.836371  15.836371 189486468\n2001-04-13 00:00:00+05:30   RELIANCE.NS  15.940308  15.940308  15.940308  15.940308         0\n2001-11-16 00:00:00+05:30   RELIANCE.NS  15.218407  15.218407  15.218407  15.218407         0\n2002-05-01 00:00:00+05:30   RELIANCE.NS  15.234822  15.234822  15.234822  15.234822         0\n2000-05-01 00:00:00+05:30       SBIN.NS  13.088063  13.088063  13.088063  13.088063         0\n2002-10-02 00:00:00+05:30       SBIN.NS  15.448785  15.448785  15.448785  15.448785         0\n2005-11-04 00:00:00+05:30       SBIN.NS  59.681915  59.681915  59.681915  59.681915         0\n2000-02-18 00:00:00+05:30  SUNPHARMA.NS  15.201955  15.201955  15.201955  15.201955   1350775\n2004-04-09 00:00:00+05:30  SUNPHARMA.NS  27.634459  27.634459  27.634459  27.634459         0\n2002-10-15 00:00:00+05:30        TCS.NS  24.218763  24.218763  24.218763  24.218763         0\n2003-03-14 00:00:00+05:30        TCS.NS  26.764318  26.764318  26.764318  26.764318         0\n2004-11-15 00:00:00+05:30        TCS.NS  95.751320  95.751320  95.751320  95.751320         0\n2004-11-26 00:00:00+05:30        TCS.NS  97.359535  97.359535  97.359535  97.359535         0'

In [44]:
invalid_without_negative.groupby('Stock').agg(
    count=('Stock', 'size'),
    first_date=('Date', 'min'),
    last_date=('Date', 'max')
)

               count                first_date                 last_date
Stock
ADANIENT.NS        1 2004-01-26 00:00:00+05:30 2004-01-26 00:00:00+05:30
ASIANPAINT.NS      1 2002-12-25 00:00:00+05:30 2002-12-25 00:00:00+05:30
BAJFINANCE.NS      1 2004-11-15 00:00:00+05:30 2004-11-15 00:00:00+05:30
HDFCBANK.NS        2 2000-04-06 00:00:00+05:30 2004-04-09 00:00:00+05:30
HINDUNILVR.NS      8 2001-04-13 00:00:00+05:30 2005-11-04 00:00:00+05:30
ICICIBANK.NS       1 2003-05-01 00:00:00+05:30 2003-05-01 00:00:00+05:30
INFY.NS           12 2000-01-07 00:00:00+05:30 2008-11-27 00:00:00+05:30
ITC.NS            11 2001-08-22 00:00:00+05:30 2004-11-26 00:00:00+05:30
LT.NS              2 2002-11-06 00:00:00+05:30 2004-04-26 00:00:00+05:30
MARUTI.NS          1 2004-04-26 00:00:00+05:30 2004-04-26 00:00:00+05:30
RELIANCE.NS        4 2000-04-04 00:00:00+05:30 2002-05-01 00:00:00+05:30
SBIN.NS            3 2000-05-01 00:00:00+05:30 2005-11-04 00:00:00+05:30
SUNPHARMA.NS       2 2000-02-18 00:00:00+05:30 2004-04-09 00:00:00+05:30
TCS.NS             4 2002-10-15 00:00:00+05:30 2004-11-26 00:00:00+05:30

In [45]:
# 1. Negative price mask
negative_mask = df[['Open', 'High', 'Low', 'Close']].lt(0).any(axis=1)

# 2. OHLC validity mask
invalid_ohlc = (
    (df['High'] < df['Open']) |
    (df['High'] < df['Close']) |
    (df['High'] < df['Low']) |
    (df['Low'] > df['Open']) |
    (df['Low'] > df['Close'])
)

# 3. Invalid OHLC rows that are NOT negative-price rows
invalid_without_negative = df[invalid_ohlc & ~negative_mask]

print("Negative price rows:", negative_mask.sum())
print("Invalid OHLC rows:", invalid_ohlc.sum())
print("Invalid OHLC excluding negative rows:", len(invalid_without_negative))

Negative price rows: 47
Invalid OHLC rows: 99
Invalid OHLC excluding negative rows: 53

In [46]:
invalid_without_negative[
    ['Date', 'Stock', 'Open', 'High', 'Low', 'Close', 'Volume']
].sort_values(['Stock', 'Date'])

,Date,Stock,Open,High,Low,Close,Volume
114924,2004-01-26 00:00:00+05:30,ADANIENT.NS,0.936609,0.936609,0.936609,0.936609,0
102614,2002-12-25 00:00:00+05:30,ASIANPAINT.NS,15.895419,15.895419,15.895419,15.895419,0
55684,2004-11-15 00:00:00+05:30,BAJFINANCE.NS,0.963990,0.963990,0.963990,0.963990,0
18403,2000-04-06 00:00:00+05:30,HDFCBANK.NS,8.301004,8.501512,7.721538,7.721538,1670120
19449,2004-04-09 00:00:00+05:30,HDFCBANK.NS,15.758716,15.758716,15.758716,15.758716,0
49061,2001-04-13 00:00:00+05:30,HINDUNILVR.NS,117.442207,117.442207,117.442207,117.442207,0
49073,2001-05-01 00:00:00+05:30,HINDUNILVR.NS,117.581879,117.581879,117.581879,117.581879,0
49154,2001-08-22 00:00:00+05:30,HINDUNILVR.NS,126.428185,126.428185,126.428185,126.428185,0
49334,2002-05-01 00:00:00+05:30,HINDUNILVR.NS,115.717690,115.717690,115.717690,115.717690,0
49453,2002-10-15 00:00:00+05:30,HINDUNILVR.NS,99.814232,99.814232,99.814232,99.814232,0
49540,2003-02-13 00:00:00+05:30,HINDUNILVR.NS,97.205048,97.205048,97.205048,97.205048,0
49841,2004-04-09 00:00:00+05:30,HINDUNILVR.NS,89.613518,89.613518,89.613518,89.613518,0
50242,2005-11-04 00:00:00+05:30,HINDUNILVR.NS,107.599220,107.599220,107.599220,107.599220,0
24892,2003-05-01 00:00:00+05:30,ICICIBANK.NS,15.767154,15.767154,15.767154,15.767154,0
11999,2000-01-07 00:00:00+05:30,INFY.NS,61.325985,61.325985,61.325985,61.325985,971392
12001,2000-01-11 00:00:00+05:30,INFY.NS,61.674072,64.477439,59.135857,59.135857,15658368
12025,2000-02-14 00:00:00+05:30,INFY.NS,100.374100,100.374100,100.374100,100.374100,1518912
12038,2000-03-02 00:00:00+05:30,INFY.NS,94.704747,95.691063,92.811069,95.691063,1607040
12069,2000-04-14 00:00:00+05:30,INFY.NS,86.631981,86.631981,86.631981,86.631981,0
12327,2001-04-11 00:00:00+05:30,INFY.NS,37.545856,38.325296,30.070351,30.070351,41200640
12451,2001-10-02 00:00:00+05:30,INFY.NS,21.803333,21.803333,21.803333,21.803333,0
12484,2001-11-16 00:00:00+05:30,INFY.NS,30.532764,30.532764,30.532764,30.532764,0
12678,2002-08-15 00:00:00+05:30,INFY.NS,29.778316,29.778316,29.778316,29.778316,0
13055,2004-01-26 00:00:00+05:30,INFY.NS,52.091019,52.091019,52.091019,52.091019,0
13112,2004-04-14 00:00:00+05:30,INFY.NS,52.401020,52.401020,52.401020,52.401020,0
14268,2008-11-27 00:00:00+05:30,INFY.NS,97.566971,97.566971,97.566971,97.566971,0
42817,2001-08-22 00:00:00+05:30,ITC.NS,7.916252,7.916252,7.916252,7.916252,0
42879,2001-11-16 00:00:00+05:30,ITC.NS,7.413278,7.413278,7.413278,7.413278,0
42970,2002-03-25 00:00:00+05:30,ITC.NS,7.676972,7.676972,7.676972,7.676972,0
42997,2002-05-01 00:00:00+05:30,ITC.NS,6.832716,6.832716,6.832716,6.832716,0
43073,2002-08-15 00:00:00+05:30,ITC.NS,7.636112,7.636112,7.636112,7.636112,0
43107,2002-10-02 00:00:00+05:30,ITC.NS,7.194844,7.194844,7.194844,7.194844,0
43132,2002-11-06 00:00:00+05:30,ITC.NS,6.947910,6.947910,6.947910,6.947910,0
43167,2002-12-25 00:00:00+05:30,ITC.NS,7.333257,7.333257,7.333257,7.333257,0
43248,2003-04-18 00:00:00+05:30,ITC.NS,7.567458,7.567458,7.567458,7.567458,0
43257,2003-05-01 00:00:00+05:30,ITC.NS,7.562476,7.562476,7.562476,7.562476,0
43666,2004-11-26 00:00:00+05:30,ITC.NS,14.697599,14.697599,14.697599,14.697599,0
36792,2002-11-06 00:00:00+05:30,LT.NS,31.635120,31.635120,31.635120,31.635120,0
37175,2004-04-26 00:00:00+05:30,LT.NS,102.114807,102.114807,102.114807,102.114807,0
78935,2004-04-26 00:00:00+05:30,MARUTI.NS,497.947632,497.947632,497.947632,497.947632,0
66,2000-04-04 00:00:00+05:30,RELIANCE.NS,17.075103,17.075103,15.836371,15.836371,189486468
334,2001-04-13 00:00:00+05:30,RELIANCE.NS,15.940308,15.940308,15.940308,15.940308,0
489,2001-11-16 00:00:00+05:30,RELIANCE.NS,15.218407,15.218407,15.218407,15.218407,0
607,2002-05-01 00:00:00+05:30,RELIANCE.NS,15.234822,15.234822,15.234822,15.234822,0
30447,2000-05-01 00:00:00+05:30,SBIN.NS,13.088063,13.088063,13.088063,13.088063,0
31079,2002-10-02 00:00:00+05:30,SBIN.NS,15.448785,15.448785,15.448785,15.448785,0
31875,2005-11-04 00:00:00+05:30,SBIN.NS,59.681915,59.681915,59.681915,59.681915,0
84184,2000-02-18 00:00:00+05:30,SUNPHARMA.NS,15.201955,15.201955,15.201955,15.201955,1350775
85264,2004-04-09 00:00:00+05:30,SUNPHARMA.NS,27.634459,27.634459,27.634459,27.634459,0
6383,2002-10-15 00:00:00+05:30,TCS.NS,24.218763,24.218763,24.218763,24.218763,0
6491,2003-03-14 00:00:00+05:30,TCS.NS,26.764318,26.764318,26.764318,26.764318,0
6925,2004-11-15 00:00:00+05:30,TCS.NS,95.751320,95.751320,95.751320,95.751320,0
6934,2004-11-26 00:00:00+05:30,TCS.NS,97.359535,97.359535,97.359535,97.359535,0

In [47]:
df.loc[negative_mask, ['Date', 'Stock', 'Open', 'High', 'Low', 'Close', 'Volume']]

,Date,Stock,Open,High,Low,Close,Volume
114514,2002-07-01 00:00:00+05:30,ADANIENT.NS,-0.012181,-0.012517,-0.011914,-0.012168,1080397
114515,2002-07-02 00:00:00+05:30,ADANIENT.NS,-0.012380,-0.012421,-0.012113,-0.012263,1016147
114516,2002-07-03 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012387,-0.012188,-0.012263,980394
114517,2002-07-04 00:00:00+05:30,ADANIENT.NS,-0.012318,-0.012517,-0.012318,-0.012332,972747
114518,2002-07-05 00:00:00+05:30,ADANIENT.NS,-0.012400,-0.012400,-0.012257,-0.012304,974496
114519,2002-07-08 00:00:00+05:30,ADANIENT.NS,-0.012455,-0.012989,-0.012188,-0.012845,1061686
114520,2002-07-09 00:00:00+05:30,ADANIENT.NS,-0.012797,-0.012866,-0.012428,-0.012510,1024719
114521,2002-07-10 00:00:00+05:30,ADANIENT.NS,-0.012592,-0.012592,-0.012387,-0.012496,946638
114522,2002-07-11 00:00:00+05:30,ADANIENT.NS,-0.012941,-0.012941,-0.012257,-0.012291,968220
114523,2002-07-12 00:00:00+05:30,ADANIENT.NS,-0.012428,-0.012530,-0.012318,-0.012387,967763
114524,2002-07-15 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012311,-0.012085,-0.012133,974157
114525,2002-07-16 00:00:00+05:30,ADANIENT.NS,-0.012181,-0.012332,-0.012181,-0.012243,959138
114526,2002-07-17 00:00:00+05:30,ADANIENT.NS,-0.012250,-0.012250,-0.012113,-0.012147,955902
114527,2002-07-18 00:00:00+05:30,ADANIENT.NS,-0.012476,-0.012476,-0.012188,-0.012291,958081
114528,2002-07-19 00:00:00+05:30,ADANIENT.NS,-0.012387,-0.012387,-0.012120,-0.012243,1022018
114529,2002-07-22 00:00:00+05:30,ADANIENT.NS,-0.012044,-0.012298,-0.011873,-0.011955,959229
114530,2002-07-23 00:00:00+05:30,ADANIENT.NS,-0.011634,-0.012174,-0.011634,-0.011955,950108
114531,2002-07-24 00:00:00+05:30,ADANIENT.NS,-0.011839,-0.011996,-0.011641,-0.011641,1004507
114532,2002-07-25 00:00:00+05:30,ADANIENT.NS,-0.011976,-0.012161,-0.011565,-0.011750,929688
114533,2002-07-26 00:00:00+05:30,ADANIENT.NS,-0.011463,-0.011463,-0.011305,-0.011387,934529
114534,2002-07-29 00:00:00+05:30,ADANIENT.NS,-0.011565,-0.011565,-0.010970,-0.011107,955236
114535,2002-07-30 00:00:00+05:30,ADANIENT.NS,-0.011565,-0.011565,-0.010949,-0.010984,972108
114536,2002-07-31 00:00:00+05:30,ADANIENT.NS,-0.011155,-0.011155,-0.010676,-0.010881,961513
114537,2002-08-01 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.011257,-0.010949,-0.011011,953331
114538,2002-08-02 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.010949,-0.010724,-0.010902,939461
114539,2002-08-05 00:00:00+05:30,ADANIENT.NS,-0.011497,-0.011497,-0.010689,-0.010881,982116
114540,2002-08-06 00:00:00+05:30,ADANIENT.NS,-0.010949,-0.010949,-0.010683,-0.010730,971195
114541,2002-08-07 00:00:00+05:30,ADANIENT.NS,-0.011086,-0.011086,-0.010847,-0.010929,966576
114542,2002-08-08 00:00:00+05:30,ADANIENT.NS,-0.011155,-0.011155,-0.010710,-0.010765,971443
114543,2002-08-09 00:00:00+05:30,ADANIENT.NS,-0.010813,-0.010915,-0.010744,-0.010847,918884
114544,2002-08-12 00:00:00+05:30,ADANIENT.NS,-0.010888,-0.010943,-0.010813,-0.010895,489590
114545,2002-08-13 00:00:00+05:30,ADANIENT.NS,-0.010908,-0.010943,-0.010813,-0.010854,384772
114546,2002-08-14 00:00:00+05:30,ADANIENT.NS,-0.010922,-0.010922,-0.010628,-0.010744,482452
114547,2002-08-15 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010744,-0.010744,-0.010744,0
114548,2002-08-16 00:00:00+05:30,ADANIENT.NS,-0.010717,-0.010813,-0.010511,-0.010573,520671
114549,2002-08-19 00:00:00+05:30,ADANIENT.NS,-0.010813,-0.010813,-0.010477,-0.010566,501059
114550,2002-08-20 00:00:00+05:30,ADANIENT.NS,-0.010669,-0.010669,-0.010539,-0.010559,507936
114551,2002-08-21 00:00:00+05:30,ADANIENT.NS,-0.010696,-0.010765,-0.010607,-0.010662,507062
114552,2002-08-22 00:00:00+05:30,ADANIENT.NS,-0.010696,-0.010778,-0.010607,-0.010696,495383
114553,2002-08-23 00:00:00+05:30,ADANIENT.NS,-0.010751,-0.010813,-0.010607,-0.010730,519588
114554,2002-08-26 00:00:00+05:30,ADANIENT.NS,-0.010806,-0.010949,-0.010655,-0.010696,552014
114555,2002-08-27 00:00:00+05:30,ADANIENT.NS,-0.010730,-0.010792,-0.010573,-0.010635,504152
114556,2002-08-28 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010744,-0.010580,-0.010655,491338
114557,2002-08-29 00:00:00+05:30,ADANIENT.NS,-0.010676,-0.010676,-0.010539,-0.010594,489146
114558,2002-08-30 00:00:00+05:30,ADANIENT.NS,-0.010594,-0.010641,-0.010546,-0.010621,488768
114559,2002-09-02 00:00:00+05:30,ADANIENT.NS,-0.010662,-0.010806,-0.010662,-0.010737,514408
114560,2002-09-03 00:00:00+05:30,ADANIENT.NS,-0.010744,-0.010758,-0.010628,-0.010710,493035

In [48]:
df.loc[negative_mask].groupby('Stock').agg(
    count=('Stock', 'size'),
    first_date=('Date', 'min'),
    last_date=('Date', 'max')
)

             count                first_date                 last_date
Stock
ADANIENT.NS     47 2002-07-01 00:00:00+05:30 2002-09-03 00:00:00+05:30

In [49]:
df_clean = df[~negative_mask].copy()

In [50]:
print("Original shape:", df.shape)
print("Cleaned shape:", df_clean.shape)
print("Rows removed:", len(df) - len(df_clean))

Original shape: (120203, 9)
Cleaned shape: (120156, 9)
Rows removed: 47

In [51]:
(df_clean[['Open', 'High', 'Low', 'Close']] < 0).sum()

Open     0
High     0
Low      0
Close    0
dtype: int64

In [52]:
df_clean['Stock'].value_counts().loc['ADANIENT.NS']

np.int64(5642)

In [53]:
df_clean['Date'] = pd.to_datetime(df_clean['Date'])

In [55]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120156 entries, 0 to 120202
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Date          120156 non-null  datetime64[ns, UTC+05:30]
 1   Stock         120156 non-null  object
 2   Open          120156 non-null  float64
 3   High          120156 non-null  float64
 4   Low           120156 non-null  float64
 5   Close         120156 non-null  float64
 6   Volume        120156 non-null  int64
 7   Dividends     120156 non-null  float64
 8   Stock Splits  120156 non-null  float64
dtypes: datetime64[ns, UTC+05:30](1), float64(6), int64(1), object(1)
memory usage: 9.2+ MB

In [56]:
df_clean.sort_values(['Stock', 'Date'], inplace=True)

In [57]:
df_clean[['Stock', 'Date']].head(10)

              Stock                      Date
114561  ADANIENT.NS 2002-09-04 00:00:00+05:30
114562  ADANIENT.NS 2002-09-05 00:00:00+05:30
114563  ADANIENT.NS 2002-09-06 00:00:00+05:30
114564  ADANIENT.NS 2002-09-09 00:00:00+05:30
114565  ADANIENT.NS 2002-09-10 00:00:00+05:30
114566  ADANIENT.NS 2002-09-11 00:00:00+05:30
114567  ADANIENT.NS 2002-09-12 00:00:00+05:30
114568  ADANIENT.NS 2002-09-13 00:00:00+05:30
114569  ADANIENT.NS 2002-09-16 00:00:00+05:30
114570  ADANIENT.NS 2002-09-17 00:00:00+05:30

In [59]:
df_clean.dtypes

Date            datetime64[ns, UTC+05:30]
Stock                              object
Open                              float64
High                              float64
Low                               float64
Close                             float64
Volume                              int64
Dividends                         float64
Stock Splits                      float64
dtype: object

In [60]:
df_clean['date_diff'] = (
    df_clean.groupby('Stock')['Date']
    .diff()
    .dt.days
)

In [61]:
df_clean['date_diff'].describe()

count    120136.000000
mean          1.467520
std           0.874795
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max           6.000000
Name: date_diff, dtype: float64

In [62]:
df_clean['date_diff'].value_counts().sort_index().head(15)

date_diff
1.0    92006
2.0     2832
3.0    22780
4.0     2318
5.0      180
6.0       20
Name: count, dtype: int64